# Generated by Django 2.0.5 on 2019-02-15 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import offers.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('image', models.ImageField(blank=True, help_text='600*400', upload_to=offers.tools.upload_location, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), offers.tools.check_size])),
                ('front_page', models.BooleanField(default=True, verbose_name='Εμφανίσιμο στην αρχικη σελίδα')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Τίτλος')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αρχίκη Αξία')),
                ('offer_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Εκπτωτική Αξία')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offer_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='offers.Offer')),
                ('product_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
