# Generated by Django 2.0.5 on 2019-02-15 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import frontend.validators
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=frontend.validators.upload_banner, validators=[frontend.validators.validate_size])),
                ('href', models.URLField(blank=True, null=True)),
                ('new_window', models.BooleanField(default=False)),
                ('big_banner', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργοποίηση')),
                ('title', models.CharField(max_length=120, verbose_name='Ονομασία Brand')),
                ('image', models.ImageField(blank=True, upload_to='brands/', verbose_name='Εικόνα')),
                ('order_by', models.IntegerField(default=1, verbose_name='Σειρά Προτεριότητας')),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(default=240)),
                ('height', models.IntegerField(default=240)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CategorySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, help_text='610*410', null=True, upload_to=frontend.validators.category_site_directory_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=1)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('show_on_menu', models.BooleanField(default=False, verbose_name='Active on Navbar')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.CategorySite')),
            ],
            options={
                'verbose_name_plural': 'Κατηγορίες Site',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to=frontend.validators.upload_location, validators=[frontend.validators.validate_size])),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(max_length=160)),
            ],
        ),
    ]
