# Generated by Django 2.0.5 on 2019-02-15 07:56

from django.db import migrations, models
import frontend.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='600*600', upload_to=frontend.validators.upload_banner, validators=[frontend.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, help_text='600*600', upload_to='brands/', verbose_name='Εικόνα'),
        ),
    ]
