# Generated by Django 2.2.4 on 2019-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20190217_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-active', '-id']},
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='mptt_level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='BrandWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('brands', models.ManyToManyField(to='frontend.Brand')),
            ],
        ),
    ]
