# Generated by Django 2.0.5 on 2019-02-15 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 7, 56, 22, 298246, tzinfo=utc)),
        ),
    ]
