# Generated by Django 2.0.5 on 2019-02-17 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20190215_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 2, 17, 8, 51, 46, 468898, tzinfo=utc)),
        ),
    ]
