# Generated by Django 2.0.7 on 2019-04-18 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20190217_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 7, 4, 34, 9932, tzinfo=utc)),
        ),
    ]
