# Generated by Django 2.0.7 on 2019-06-05 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20190418_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 7, 44, 44, 555337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentorders',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
