# Generated by Django 2.0.7 on 2019-06-05 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20190605_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 7, 51, 28, 831720, tzinfo=utc)),
        ),
    ]
