# Generated by Django 2.2.4 on 2019-12-04 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_auto_20191020_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 17, 22, 34, 972164, tzinfo=utc)),
        ),
    ]
