# Generated by Django 2.0.7 on 2019-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.BooleanField(default=False),
        ),
    ]
