# Generated by Django 2.0.7 on 2019-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190418_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='title',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
